apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rui4a5ol7-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rui4a5ol7-python 
  name: rui4a5ol7-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rui4a5ol7-python 
